sudo: required
services:
  - docker 

before_install:
  - docker build -t shafik/docker-react -f Dockerfile.dev . 

script:
  - docker ps -a
  # npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-306419907743"
#   bucket_path: "docker-react"
#   on: 
#     branch: master
    